# Generated by Django 5.2.8 on 2025-12-23 11:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('incident_type', models.CharField(choices=[('fire', 'Fire'), ('flood', 'Flood'), ('landslide', 'Landslide'), ('accident', 'Accident'), ('other', 'Other')], default='other', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('in_rescue', 'In Rescue'), ('resolved', 'Resolved')], default='reported', max_length=30)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='incident_media/%Y/%m/%d/')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='incidents.incident')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='incidents.incident')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_done', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incidents_i_status_9a4f12_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['incident_type'], name='incidents_i_inciden_337dba_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['-created_at'], name='incidents_i_created_c4c91a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incidentverification',
            unique_together={('incident', 'verified_by')},
        ),
    ]
