# Generated by Django 5.2.8 on 2025-12-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='longitude',
        ),
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.CharField(default='Unknown location', max_length=255),
        ),
    ]
