# Generated by Django 5.2.8 on 2025-12-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_remove_incident_latitude_remove_incident_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
