# Generated by Django 5.2.8 on 2026-01-05 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_of_family_name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('total_members', models.PositiveIntegerField()),
                ('injured_members', models.PositiveIntegerField(default=0)),
                ('deceased_members', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_families', to='incidents.incident')),
            ],
        ),
        migrations.CreateModel(
            name='LossAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_damage', models.CharField(choices=[('none', 'No Damage'), ('partial', 'Partial Damage'), ('full', 'Fully Damaged')], max_length=50)),
                ('estimated_property_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('livestock_lost', models.PositiveIntegerField(default=0)),
                ('crops_lost', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loss_assessment', to='assessments.affectedfamily')),
            ],
        ),
    ]
