# Generated by Django 5.2.8 on 2025-12-23 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('money', 'Money'), ('item', 'Item')], max_length=10)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('item_description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_donations', to='assessments.affectedfamily')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_donations', to='incidents.incident')),
            ],
        ),
        migrations.CreateModel(
            name='DonationDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_photo_url', models.URLField(blank=True, null=True)),
                ('distributed_at', models.DateTimeField(auto_now_add=True)),
                ('distributed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributed_donations', to=settings.AUTH_USER_MODEL)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='donations.donation')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_donations', to='assessments.affectedfamily')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donations.donor'),
        ),
    ]
