# Generated by Django 5.2.8 on 2026-02-11 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_add_verification_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='verified_by',
        ),
    ]
